### ISSUE TITLE
How to use change different values

### ISSUE THREAD

**Issue by 2stimpy** [romahony/mqtt_blinds#1]
This is a great example.
I got this working in my setup but i have a few questions.
My blinds only go closed or almost 90 degrees open.
I would like to have them opening a little more. What value should i change, or can't is be done.

Other thing is that i would like to change the operation because at one blind i can mount t left and on another it needs to be on the right side. so it should operate mirrored from the other.

In home assist there is an "cover" command to use for tilt but i cant seem to get that working right. it does operate the blinds but there is no state. Plus in the app the tilt function does not show up.

I hope you can point me in the right direction,
Thanks,

**Comment by romahony** [comment]
New versions have been added for normal and reverse.
